# Defaults for image training.

image_size: 256
num_channels: 128
num_res_blocks: 2
channel_mult: [1, 1, 2, 2, 4, 4]
learn_sigma: False
class_cond: False
use_checkpoint: False
attention_resolutions: 16
num_heads: 1  # 4
num_head_channels: 128  # 64 actually: 128*ch_mult[i_level]
num_heads_upsample: -1
use_scale_shift_norm: False
dropout: 0.0
resblock_updown: False
use_fp16: True
use_new_attention_order: False

model_path: ../../checkpoints/celeba_hq.ckpt
